[workspace]
resolver = "3"
members = ["crates/*", "xtask"]

[workspace.package]
version = "0.1.0"
edition = "2024"
repository = "https://github.com/yegorvk/isoplot"
license = "MPL-2.0"

[workspace.dependencies]
# Workspace
isoplot-mesh = { path = "crates/isoplot-mesh", version = "0.1.0" }

# External
anyhow = "1.0"
arrayvec = "0.7.6"
bilge = "0.3.0"
dashmap = "6.2.1"
derive-where = "1.6.1"
glam = "0.32.1"

[profile.dev.package.isoplot-bevy]
opt-level = 1

[profile.dev.package.isoplot-mesh]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "thin"

[profile.dev-opt]
inherits = "release"
lto = "off"
