[package]
name = "isoplot-eval"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
logos = "0.16.1"
thiserror.workspace = true

[dependencies.cranelift]
version = "0.134.2"
optional = true
features = ["jit", "module", "native"]

[features]
default = ["default-fallback"]
cranelift = ["dep:cranelift"]
default-fallback = []
default-cranelift = ["cranelift"]
