[package]
name = "isoplot-bevy"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
isoplot-expr.workspace = true
isoplot-mesh.workspace = true
glam.workspace = true
bytemuck = "1.25.0"
dashmap.workspace = true
noise = "0.9"

[dependencies.bevy]
version = "0.19.0"
default-features = false
features = [
    "default_app",
    "default_platform",
    "3d_bevy_render",
    "bevy_log",
    "ui_bevy_render",
    "bevy_ui_widgets",
    "ui_picking",
    "default_font",
]

[dependencies.log]
version = "*"
features = ["max_level_debug", "release_max_level_warn"]
