[package]
name = "isoplot-math"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
derive-where.workspace = true
fearless_simd.workspace = true
fearless_simd_macros.workspace = true
itertools.workspace = true

[dependencies.bytemuck]
workspace = true
features = ["derive", "min_const_generics", "must_cast"]
